### ISSUE TITLE
E-Sword Import

### ISSUE THREAD

**Issue by doxaPar** [schierlm/BibleMultiConverter#10]
It isn't clear to me if import from E-Sword format is possible. Can you provide details? Thanks

**Comment by schierlm** [comment]
Hello,

import from E-Sword (like from Logos) is not possible at the moment.

Main obstacle is that E-Sword uses RTF to store its formatting. And I don't know any good free robust RTF parsers for Java (OpenOffice is probably a bit too heavyweight just for converting from a Bible).

Also, in my experience, E-Sword modules tend to be of lower quality than other formats (they do not support footnotes, have a fixed versification, and also the support for formatting is worse than for other Bible formats), so I would prefer to convert from another source anyway, if available.

If you really want to get the text out of an E-Sword module, you are probably best off exporting it with ToolTipTool NT and then manually editing it to another supported format.

**Comment by doxaPar** [comment]
Thank you!
