### ISSUE TITLE
mvn dependency jsword

### ISSUE THREAD

**Issue by sscholl** [schierlm/BibleMultiConverter#12]
For a successful build you need to build [crosswire/jsword](https://github.com/crosswire/jsword) before, to have the jsword-2.1-SNAPSHOT.jar in local repo. The 2.1 tag will not produce this version. Commit 3db8802db3f94ec42b2201b65f6965de0e8c9d52 -DskipTests=true was successful.

Please remove dependency or document in Readme.md

**Comment by schierlm** [comment]
Thanks for the reminder. When I first added SWORD support in 2015, I expected that there would soon be an official release of JSword which would also get loaded to Maven Central. But it seemed that this never happened.

For the record, the commit I built and used was crosswire/jsword@fa6a44d05982a67f0122ffdd7b522d8ebcf43824

**Comment by sscholl** [comment]
Oh wow. That was a fast answer. :)
