### ISSUE TITLE
Unclear from usage output what `[ExportArgs...]` are

### ISSUE THREAD

**Issue by n9yty** [schierlm/BibleMultiConverter#13]
Sorry, failure on my part.  :(

**Comment by schierlm** [comment]
No problem. Add an output file name and it should work :)

**Comment by renehamburger** [comment]
I made the same mistake. It would be good to add this to the command line help: `java -jar BibleMultiConverter.jar <ImportFormat> <ImportFile> <ExportFormat> [<ExportArgs>...]`.

**Comment by renehamburger** [comment]
Yes, sorry, that wasn't very clear what I wrote there. That's the exact line from your command line help, but it does not mention `<ExportFile>`. It seems that a more complete command description would be `java -jar BibleMultiConverter.jar <ImportFormat> <ImportFile> <ExportFormat> <ExportFile> [<ExportArgs>...]`
It's also not clear what the optional `<ExportArgs>` are. Are they documented anywhere outside the sources?

**Comment by schierlm** [comment]
Export args are shown when you call 

`java -jar BibleMultiConverter.jar help <ExportFormat>`

Some formats don't have an export file, but an export directory, or two export files, or some extra parameters (to choose *how* to export it).
