### ISSUE TITLE
QuickBible export not working

### ISSUE THREAD

**Issue by mcarans** [schierlm/BibleMultiConverter#16]
I am not able to export for example https://mybible.zone/dlbiblel.php?a=1141&b=1 to QuickBible. It seems to complete successfully but when I try to load it in QuickBible, it says "Not a valid yes file"

**Comment by schierlm** [comment]
QuickBible exporter produces YET file, not YES file. You have to convert YET to YES with the tool available on QuickBible homepage.

If you still get any errors, I'll be glad to have a closer look at that particular module.

**Comment by mcarans** [comment]
Thanks, I did not realise this. It would be good to make this clear in the help.
