### ISSUE TITLE
Can't open BibleMultiConverter

### ISSUE THREAD

**Issue by juniju1** [schierlm/BibleMultiConverter#18]
Good afternoon, I am not sure if this is the right place to ask for some help but I downloaded the latest converter and I can seem to make it work. I downloaded the latest java and configured my windows 10 to run it but it is not loading up. Could someone please help me get it to load. I don't know what I am dong wrong. Thanks.
Juniju

**Comment by schierlm** [comment]
Quite unclear bug report. :-(

- You are aware that you have to start it in a command line window? (Ok, on Windows you probably could also try PowerShell, but its powers won't help you here much)

- When you do so, what output do you get? On Windows, you have to right-click the title bar to get a menu where you can copy and paste the text. If you don't get that to work, you can also create a screenshot and attach it here (just press Ctrl+V in the comment window and GitHub will attach it).

**Comment by juniju1** [comment]
Thank you for the quick response. I really appreciated. I do not know how to start it in command line. Can you help me please?
Jean

**Comment by schierlm** [comment]
https://www.wikihow.com/Run-Exe-from-Cmd-on-PC-or-Mac

Instead of `start Explorer` you use `java -jar BibleMultiConverter.jar`

Then after you read the output, add arguments at the end (format names and file names).

**Comment by juniju1** [comment]
I did and this is what I get:
C:\Users\jgilb>java -jar BibleMultiConverter.jar
Error: Unable to access jarfile BibleMultiConverter.jar

C:\Users\jgilb>

I also tried to locate the folder where the files are but i got the same results
C:\Users\jgilb\Desktop\New folder>java -jar BibleMultiConverter.jar
Error: Unable to access jarfile BibleMultiConverter.jar

C:\Users\jgilb\Desktop\New folder>

I don't know why it is not loading.

**Comment by juniju1** [comment]
I got it to work. Yes! but I still need some more help. I don't know what you mean by add arguments at the end (format names and file names). Do yo mean the file I want to convert?

**Comment by schierlm** [comment]
The file you want to convert and the file you want to get out. Also the formats of those files.

For example:

    java -jar BibleMultiConverter.jar ZefaniaXML kjv.xml MyBibleZone kjv.sqlite3

to convert Zefania XML version of the King James Version to MyBibleZone format and name the output file `kjv.sqlite3`.

**Comment by juniju1** [comment]
Thank you very much for all you do. God bless.
