### ISSUE TITLE
TheWord Commentary doesn't convert to MyBibleZone

### ISSUE THREAD

**Issue by Rrrrralph** [schierlm/BibleMultiConverter#19]
This is a testfile I generated for TheWord. Trying to convert isn't successful.
What am I doing wrong here ? Do I need to set any specific module settings for TheWord ?
[ABC.cmt.zip](https://github.com/schierlm/BibleMultiConverter/files/2138090/ABC.cmt.zip)

**Comment by schierlm** [comment]
BibleMultiConverter can only convert Bible (i.e. Scripture) modules, no
commentaries or harmonies or dictionaries or devotionals or anything
else that is supported by some Bible programs.

The only exception being Strong Dictionaries, but here I only support 4
formats (ZefDic, MyBibleZone, Logos, MobiPocket).

The functionality of these other module types is vastly different
between formats, so conversion (in a generic case) is a lot harder there
than it is for Bible modules.


Sorry to disappoint you.
