### ISSUE TITLE
Error when trying to convert a MyBible module to the word

### ISSUE THREAD

**Issue by WJSwanepoel** [schierlm/BibleMultiConverter#20]
Hi, When trying to convert MyBible module to theWord I get following error:

C:\MBCTest>java -jar BibleMultiConverter.jar MyBibleZone HSV17.SQLite3 TheWord HSV
Exception in thread "main" java.lang.IllegalArgumentException: value is invalid: i  { color: %COLOR_BLUE%; }
em { color: %COLOR_BLUE%; }
a  { text-decoration: none; }
span.sc { font-variant: small-caps; }
span.pn { text-decoration: underline; }
span.RTL { direction: rtl; display: inline; }
        at biblemulticonverter.data.Utils.validateString(Utils.java:32)
        at biblemulticonverter.data.MetadataBook.setValue(MetadataBook.java:67)
        at biblemulticonverter.sqlite.format.MyBibleZone.doImport(MyBibleZone.java:157)
        at biblemulticonverter.Main.main(Main.java:61)

C:\MBCTest>

Can you perhaps assist?

**Comment by WJSwanepoel** [comment]
> Hi, When trying to convert MyBible module to theWord I get following error:
> 
> C:\MBCTest>java -jar BibleMultiConverter.jar MyBibleZone HSV17.SQLite3 TheWord HSV
> Exception in thread "main" java.lang.IllegalArgumentException: value is invalid: i { color: %COLOR_BLUE%; }
> em { color: %COLOR_BLUE%; }
> a { text-decoration: none; }
> span.sc { font-variant: small-caps; }
> span.pn { text-decoration: underline; }
> span.RTL { direction: rtl; display: inline; }
> at biblemulticonverter.data.Utils.validateString(Utils.java:32)
> at biblemulticonverter.data.MetadataBook.setValue(MetadataBook.java:67)
> at biblemulticonverter.sqlite.format.MyBibleZone.doImport(MyBibleZone.java:157)
> at biblemulticonverter.Main.main(Main.java:61)
> 
> C:\MBCTest>
> 
> Can you perhaps assist?

**Comment by schierlm** [comment]
What version of BibleMultiConverter are you using? The error output does not match the output from latest version (0.0.6).

Also, could you share the input module? I tried with the HSV17 one from http://bible.ph4.ru/ and it converted fine (with lots of warnings, but harmless ones). You can zip the file and attach to this ticket.

For reference, find attached the HSV17 module I converted.

[HSV.ont.zip](https://github.com/schierlm/BibleMultiConverter/files/2439233/HSV.ont.zip)
