### ISSUE TITLE
Konvertierung nicht möglich

### ISSUE THREAD

**Issue by ulli5** [schierlm/BibleMultiConverter#27]
Ich habe die Volxbibel von https://bibel.github.io/ heruntergeladen und nach BibleMultiConverter-AllInOneEdition-0.0.6 extrahiert. Die anschließende Konvertierung lief wie folgt ab:

D:\Downloads\Programme\TheWordInstall\DeutscheBibelnHTML\BibleMultiConverter-AllInOneEdition-0.0.6>java -jar BibleMultiConverter-AllInOneEdition.jar RoundtripHTML "Volxbibel-RoundtripHTML" TheWord
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at biblemulticonverter.format.TheWord.doExport(TheWord.java:290)
        at biblemulticonverter.Main.main(Main.java:67)

Ich bin blutiger Anfänger. Mache ich das was falsch?

**Comment by schierlm** [comment]
Packe hinten noch einen Dateinamen hin, wie die Zieldatei heißen soll, dann sollte es durchlaufen.

[Ich möchte hier trotzdem darauf hinweisen, dass ich das Konvertieren von urheberrechtlich geschützten Bibeln die sich gegen den Willen der Rechteinhaber auf irgendwelchen Internetseiten befinden (siehe auch `github.com/bibel/bibel.github.io/issues/1`) nicht gutheiße und hierfür keinen Support anbieten möchte.]
