### ISSUE TITLE
GUI interface

### ISSUE THREAD

**Issue by yangshulin2019** [schierlm/BibleMultiConverter#28]
Hello, schierlm, thanks for your work for this tool. Can you make some advance to build a GUI interface? The command line is a bit of hard to use.

**Comment by schierlm** [comment]
I do not plan to add a GUI interface. To be honest, providing all the options it will also be a bit hard to use. And when it only provides basic options, people will be unhappy as their favourite options are not there.

That being said, if anyone else tries to add one, Pull Requests would be welcome.

**Comment by RayReddingtonx** [comment]
I don't know where do we write the code, and if the Biblemulti converter is a software? I need to learn to convert SQlite3 modules or any such into XML for theWord. Are we supposed to install the Java managment software to run the codes? Please clarify and assist.

**Comment by schierlm** [comment]
@RayReddingtonx Please do not "Hijack" other issues for your questions. Yes, it is a software (without graphical user interface) and you need Java to run it. Latest download is [here](https://github.com/schierlm/BibleMultiConverter/releases/tag/v0.0.8).

SQlite is used by different bible programs and slightly incompatible (e.g. MyBible.Zone, MySword), and theWord does not use (Zefania?) XML any longer but their own text-based format. Conversion from MyBible.Zone to TheWord is supported, as well as MyBible.Zone to ZefaniaXML, or MySword to TheWord.

**Comment by RayReddingtonx** [comment]
thank you for replying. I thought of converting MyBible modules of
dictionary lexicons to XML to convert that into theWord by the theWord's
converter software. Are you saying we can directly convert SQlite3 into
theWord module through Java? Is it difficult to do? I am at complete loss
they have not given basic info for the beginners. There are many modules on
the ph4 site including lexicons that are not available elsewhere.

**Comment by RayReddingtonx** [comment]
Can you give me the link to download Java and how big is that file? I hope
its easy to work with.

**Comment by RayReddingtonx** [comment]
thank you for replying. I thought of converting MyBible modules of
dictionary lexicons to XML to convert that into theWord by the theWord's
converter software. Are you saying we can directly convert SQlite3 into
theWord module through Java? Is it difficult to do? I am at complete loss
they have not given basic info for the beginners. Is this the Java to download? https://java.com/en/download/windows_manual.jsp

**Comment by schierlm** [comment]
Hello @RayReddingtonx,

BibleMultiConverter can **only convert Bible texts** (= Scripture), not commentaries or dictionaries. So it won't be of any use if you want to convert dictionaries or lexicons.

**Comment by RayReddingtonx** [comment]
thank you man, I am very disappointed.
