### ISSUE TITLE
YouVersion

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [schierlm/BibleMultiConverter#29]
I am successfully converting MyBible modules, though not without hickups, into TheWord, BWT...
my question is about YouVersion.

Any clue on how to convert into YouVersion format?

**Comment by schierlm** [comment]
I am not aware that YouVersion provides any support for adding your own bibles. What platform are you talking about? I just opened the Windows 10 version again and was unable to find any way of adding a bible.

**Comment by viktor-zhuromskyy** [comment]
Copying modules into proper youversion modules is OK on Android device.
My question was about the file format of the YouVersion. Is there anyone having the info on their undocumented modules format?

**Comment by schierlm** [comment]
My question was not whether you can copy modules you downloaded from YouVersion onto another YouVersion device, but whether YouVersion allows you to add your own (=different) bibles. The ones available for download on Android (there is no download option on Windows) are encrypted (probably for DRM reasons) and in my jurisdiction it is not legal to break encryption when it was used for DRM reasons. So no export from YouVersion to another format. And if there is no option to add other bibles than the ones already available, there is no point for me in supporting importing to YouVersion from another format either.

**Comment by youversion-dl** [comment]
- look
- https://youversion-dl.github.io/
- enjoy
