### ISSUE TITLE
[request] new release?

### ISSUE THREAD

**Issue by eleius** [schierlm/BibleMultiConverter#33]
Latest available release is from Oct 2019, can you please upload a more recent one for those among us who can't compile this project on their own? Thanks in advance

**Comment by schierlm** [comment]
Recently, I haven't been able to perform as much (regression) testing as I'd like to do before a release. And I am not a fan of a forced semi-annual release cadence when you effectively have to tell people to try the last few releases to find one that works for them.

Anyway, if you don't mind the bleeding edge, here is a compiled version of a9326c3444001d5cb41df41defb43c4394057b71:

[BibleMultiConverter-a9326c3.zip](https://github.com/schierlm/BibleMultiConverter/files/4496662/BibleMultiConverter-a9326c3.zip)
[BibleMultiConverter-AllInOneEdition-a9326c3.zip](https://github.com/schierlm/BibleMultiConverter/files/4496663/BibleMultiConverter-AllInOneEdition-a9326c3.zip)

In case it does not work for your use case, you probably have to try the 0.0.7 release (and please open a bug report here).

That being said, there will of course be new releases later, but most lkely not before Q3/Q4 2020.

**Comment by eleius** [comment]
Thanks!

**Comment by schierlm** [comment]
We can leave this open until I find time to actually create the release.

**Comment by eleius** [comment]
Can we have a new compiled version of current git, please? (I can't do it myself as I don't know anything about Java)

**Comment by schierlm** [comment]
Current plans for new release are for Start/mid June.

Here is a link that always points to a compiled version of current git (if it compiles):

https://nightly.link/schierlm/BibleMultiConverter/workflows/main.yaml/master/BibleMultiConverter-AllInOneEdition-Release.zip

**Comment by schierlm** [comment]
I forgot to update this issue when I released https://github.com/schierlm/BibleMultiConverter/releases/tag/v0.0.8 last week...
