### ISSUE TITLE
Improve checking of export arguments to avoid exceptions

### ISSUE THREAD

**Issue by rkazakov** [schierlm/BibleMultiConverter#35]
Hi @schierlm!

Thanks for fantastic effort in working on this project!

I am trying to import a sample of MyBible module and convert it into Logos.

I run

```
java -jar BibleMultiConverter-AllInOneEdition.jar MyBibleZone ./AGP.SQLite3 LogosHTML
```

and get this output:

```
WARNING: Unclosed <J> tag at:
WARNING: Unclosed <J> tag at:
WARNING: Unclosed <J> tag at:
WARNING: Unclosed <J> tag at:
WARNING: Unclosed <J> tag at:
WARNING: Unclosed <J> tag at:
WARNING: Unclosed <J> tag at:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at biblemulticonverter.logos.format.LogosHTML.doExport(LogosHTML.java:196)
	at biblemulticonverter.Main.main(Main.java:67)
```

Import file attached: [AGP.zip](https://github.com/schierlm/BibleMultiConverter/files/4694002/AGP.zip)

Thanks for your help!

Ruslan

**Comment by rkazakov** [comment]
Sorry, I figured that out! I was missing an export file argument 😀

**Comment by schierlm** [comment]
Export argument documentation was improved in #34 already. Better error messages are always possible, but since every format needs a different number of export arguments, it would require changing all the modules and therefore is not a fast&simple fix.

**Comment by rkazakov** [comment]
Thanks for your reply!
All the best with this helpful project!
