### ISSUE TITLE
Charset lost from SWORD to YCHPalmBible

### ISSUE THREAD

**Issue by OSDVF** [schierlm/BibleMultiConverter#36]
I'm trying to convert CzeCEP module from SWORD to YCHPalmBible and some chars as 'ů' or 'č' are being lost even that there is a ENCODE="Cp1252" attribute in the PARSERINFO tag. I tried to converting whole SWORD module (which is in UTF-8) to windows-1252 with no success. Any soultions?

**Comment by schierlm** [comment]
Thank you for your bug report.

The characters get lost as the encoding used by my exporter is [cp1252](https://en.wikipedia.org/wiki/Windows-1252) which does not include those characters.

All Palm models I ever owned were European EFIGS models (supporting English French Italian German Spanish) and they did not support any other character set than cp1252 (which also means you can neve see an `ů` or `č` on them) so I could never implement any other charsets.

I guess that Czech PalmOS might use cp1250 encoding, but I am not sure.

If you can provide insight about PalmOS models that support Czech language (or could even dump a ROM of one of them that could be used in Palm OS Emulator), I might implement other charsets.

You may also try changing the charset name in [these two lines](https://github.com/schierlm/BibleMultiConverter/blob/master/biblemulticonverter/src/main/java/biblemulticonverter/format/YCHPalmBible.java#L60-L61), but no guarantee it will work on your Palm device.

**Comment by OSDVF** [comment]
I'll try changing the two lines and we'll se... Thank you

**Comment by OSDVF** [comment]
I wass succesfull to compile the basic BibleMultiConverter version but I'm curious about how to include SWORD import module...

**Comment by OSDVF** [comment]
Yeah, it works now. (Btw. I use [BibleConverter](https://sourceforge.net/projects/palmbibleplus/files/zBibleConverter/Mr.%20Poon_s%20BibleConverter/) to convert to binary PDB format)

**Comment by schierlm** [comment]
Closing issue :-)
