### ISSUE TITLE
Add support for exporting to Quick Bible yet format

### ISSUE THREAD

**Issue by yukuku** [schierlm/BibleMultiConverter#4]
Quick Bible is a mildly-popular open-source Bible app for Android. Custom Bible translations can be made from text-based YET files. Please support it according to http://www.bibleforandroid.com/developer.

**Comment by schierlm** [comment]
As you seem to be the developer of that app, a few questions after I read through the specification:

- Reordered or Split Verses are not supported? Are there any conventions how to best create them? If not, I'd use italic numbers in parentheses
- Is there a way to escape a literal @ symbol inside a verse that uses formatting? If not, are there any conventions what to replace it by?
- Introduction texts for books/chapters are not supported?
- Deuterocanonical books are not supported?

Thanks for the feedback.

**Comment by yukuku** [comment]
@schierlm Thanks for reading through the docs!

1. Reordered or Split Verses are not supported? 

No, it is not possible to reorder verse or split verses. 
You can skip verses by putting a verse line with empty text.
Yes, so far other versions have overcome this by putting the printed verse number in parenthesis.

2. Is there a way to escape a literal @ symbol inside a verse that uses formatting? If not, are there any conventions what to replace it by?

No. I didn't expect the '@' literal will appear on Bible text. If needed, you can use
U+FE6B ﹫ SMALL COMMERCIAL AT

3. Introduction texts for books/chapters are not supported?

No. Use pericope heading for that instead.
e.g.: pericope 2 1 1 Title text
to show "Title text" at the beginning of Exodus 1.

4. Deuterocanonical books are not supported?

They are supported. 
The book numbers for those books are custom, though:
https://github.com/yukuku/androidbible/blob/develop/publication/doc/book%20numbers.txt

**Comment by schierlm** [comment]
Thanks for the feedback. I decided not to use pericope headings for introduction texts, since those texts tend to be rather long (several paragraphs) and they mostly get in the way since usually they are not that interesting (''MyBible for Android'' provides a link to open them on demand, so they don't get in the way). I therefore decided to skip them on export.

**Comment by yukuku** [comment]
@schierlm Thank you for supporting Quick Bible format! I will mention this project on Quick Bible developer documentation.
