### ISSUE TITLE
Where Is The Download Link Of .jar File Of This Sofwtare ?

### ISSUE THREAD

**Issue by vikramght** [schierlm/BibleMultiConverter#40]
Where Is The Download Link Of .jar File Of This Sofwtare ?

**Comment by schierlm** [comment]
On the main project page, click "Releases" in the right sidebar, then click 0.0.7, You will find 5 ZIP files for download that correspond to the available "editions". When in doubt and download size does not matter, choose the all-in-one edition: https://github.com/schierlm/BibleMultiConverter/releases/download/v0.0.7/BibleMultiConverter-AllInOneEdition-0.0.7.zip
