### ISSUE TITLE
OnLineBible - blank verses

### ISSUE THREAD

**Issue by Michahel** [schierlm/BibleMultiConverter#43]
BibleMultiConverter creates an exp file with blank verses. If there is no verse in the input file, BibleMultiConverter nevertheless uses `$$$ <Verse reference>` for it.

For example, if the source file does not contain verse Le 14:57, then BibleMultiConverter still places the **$$$ Le 14:57** marker, after which there is no text, but the next verse marker is **$$$ Le 15:1**. This poses a problem when importing into the Online Bible program. Is it possible to make changes so that blank markers are not outputed into the exp file?

**Comment by schierlm** [comment]
This bug report is interesting. Could you share what version of OnLineBible you are using?

I'm asking because about 5 years ago I made the exact opposite change, to make sure that every verse part of KJV versification is always exported, even if missing or empty.

And do you know if this only affects verses at the end of the chapter, or also verses in the middle of the chapter?

So if, for example, a Bible does not have 1John 5:8 but it has 1John 5:9, do you want an empty verse 1John 5:8 or not?

What about entirely missing chapters or books?

[I am not a user of OnLineBible, so I have to rely on bug reports to find out what is wrong and how to fix it best]

**Comment by Michahel** [comment]
I received the following information from the Online Bible project leader Larry Pierce:

>During Import of a Verse Note in EXP format, you can remap the verse numbers to standard ones. Create a file xxx.RMP in the same directory as your EXP file. (Replace xxx with the name of the module being imported.) The format is as follows: 
>old verse number   new verse number
e.g.
>1Sa 20:42 1Sa 20:43
1Sa 23:29 1Sa 24:1
1Sa 24:1 1Sa 24:2
1Sa 24:10 1Sa 24:11
1Sa 24:11 1Sa 24:12
1Sa 24:12 1Sa 24:13
1Sa 24:13 1Sa 24:14
>Whenever the old reference is found it is replaced by the new reference. The compare is case insensitive and extra blanks are ignored. Book names must match exactly to what your import file is using. For Bible texts the remapped verse numbers are in brackets e.g. (20:34) 
>This is of primary use for importing European Bible versions with non-standard verse numbering.

I am using this technology. It is in this case that the problem that I am complaining about occurs. In any case, the import succeeds, even if there is only one verse in the exp file. The Online Bible creates a Missing.Lst file that contains a list of missing verses. In short, the Online Bible supports the import of an arbitrary range of verses. As I said, it can be just one verse.

**Comment by schierlm** [comment]
Good to know that OnLineBible has a remap feature as well. BibleMultiConverter can import versification mappings from e.g. SWORD bibles and also apply them to any other imported bibles.

Do you think there is a need to support export of versification mappings as RMP files (or import them)? If you e.g. want to convert a SWORD bible that includes a KJV mapping, you can probably as well apply the mapping to the bible before exporting it, or does it have any different effect (like somehow keeping shadow verse numbers)?

**Comment by schierlm** [comment]
Had to give the fix a second try. Even if you don't export blank verses, you would probably get into trouble when verses outside KJV versification get merged. So I added an `IgnoreKJV` export argument which you can set to just export all numbers as they are.

**Comment by Michahel** [comment]
>Do you think there is a need to support export of versification mappings as RMP files (or import them)? If you e.g. want to convert a SWORD bible that includes a KJV mapping, you can probably as well apply the mapping to the bible before exporting it, or does it have any different effect (like somehow keeping shadow verse numbers)?

A very interesting idea.
When I finish converting we can discuss this more.

In the meantime, I want to provide more information on how the remapping of the verse numbers works.

The remapping works not only with whole verses but also with partial verses:
1. The verse is broken up into two parts.
   The first or the second part remains with the standard numeration and
   the other part moves to the next or the previous verse.
   In the EXP file it is necessary to form such a verse as two separate verses with the same numeration.
   For example:

    $$$ Le 14:55 <2009/07/31 13:35>
    i o prokaze 6883 na odezhde 899 i na dome 1004,
    $$$ Le 14:55 <2009/07/31 13:35>
    i ob opukholi 7613, i o lishayakh 5597, i o pyatnakh 934,—

   In the file xxx.RMP there must be a line which shows a new verse number for one of the parts:
    Le 14:55 Le 14:56
   Which of these two parts remains with the original numeration is automatically determined.
2. Two or three verses are joined into one verse.
   For example:

    Ps 11:1 Ps 12:1
    Ps 11:2 Ps 12:1

   or

    Ps 50:1 Ps 51:1
    Ps 50:2 Ps 51:1
    Ps 50:3 Ps 51:1
