### ISSUE TITLE
OnLineBible - Unicode

### ISSUE THREAD

**Issue by Michahel** [schierlm/BibleMultiConverter#44]
BibleMultiConverter creates the exp file in plain ASCII or ANSI format.
Any module containing characters greater than #127 should be in UTF8 format. 
Otherwise, not all unicode characters are converted correctly.

**Comment by schierlm** [comment]
Do you know if there is a minimum version of OnLineBible that supports UTF-8? Or would it harm to just create UTF-8 in all cases?

**Comment by Michahel** [comment]
> Do you know if there is a minimum version of OnLineBible that supports UTF-8?

The latest non-Unicode version of Online Bible is 3.00. It is intended for users with Windows 98. Release 3.99 and newer is the unicode version. But on the official site, the ability to download older versions is not provided. Only the latest version is available for download. 

> would it harm to just create UTF-8 in all cases?

Yes, it should be done very easy! I see no reason to support the old non-Unicode version, because if necessary, the user can simply use the capabilities of NotePad.

**Comment by schierlm** [comment]
Thanks for your feedback. Should export UTF-8 now in all cases.
