### ISSUE TITLE
Can you plz create NHEB module for theWord?

### ISSUE THREAD

**Issue by RayReddingtonx** [schierlm/BibleMultiConverter#53]
NHEB an excellent ESV like translation is free and now has released an NHEB2021 version, I found on MyBible, with many footnotes. But its site is not working https://nheb.net . I would love to have it on theWord, it is a must.

**Comment by schierlm** [comment]
It took some manual work to fix all the raw HTML and whitespace errors in this module, but I got it to a shape that could be converted to TheWord.

[NHEB21.zip](https://github.com/schierlm/BibleMultiConverter/files/6833547/NHEB21.zip)

Contains both the .ont file for TheWord and the intermediary .bmc file in case anyone else wants to convert it to another format.
In case you are disappointed of the quality, maybe ask `Oleg Safonov (E-mail: osafonov at gmail.com, Telegram: @osafonov)` who created the original MyBible module.

Also note that the introduction text got lost in the TheWord conversion, find it below
[Intro_1.html.zip](https://github.com/schierlm/BibleMultiConverter/files/6833560/Intro_1.html.zip)

**Comment by RayReddingtonx** [comment]
Thank you Michael. I found out they are providing the NHEB but on a
different section that allows some donation, I will check that later if
that's the latest with the footnotes; and your file too, it should
circulated elsewhere.
https://www.thewordbooks.com/index.php/product/new-heart-english-bible/ as
an appreciation resource price ranges from $0 - $20
