### ISSUE TITLE
"loadBrowser failed" error in MySword

### ISSUE THREAD

**Issue by eleius** [schierlm/BibleMultiConverter#55]
I'm still having issues with conversion to mysword format. When I use BibleMultiConverter-AllInOneEdition to convert a Bible module from either the Zefania format or the OSIS format to mysword, the resulting module produces the error message _"loadBrowser failed for type 0. replacement == null"_ when opened in MySword (v12.1).

If I convert the same Zefania module to theword format using the [TheWord Importer tool](https://www.theword.net/index.php?article.tools&l=english), and then to mysword format using [MySword Migration Tools](https://www.mysword.info/download-mysword/migration-tools), the Bible module loads fine.

(Edit: I can send you the source module if needed)

**Comment by schierlm** [comment]
I noticed that recent MySword versions will refuse to load modules if they do not contain an abbreviation (`unable to invoke StartsWith method on null`), but from a quick test of converting several modules, I could not reproduce your exact error message.

Can you please re-test with latest git version? If the error persists, please try to reduce the text to one book, or one chapter, or even one verse that still reproduces the issue and then send me either the source file or the converted output file (you can attach files to this issue).

If you are not allowed to share the module text, you can try running it through ScrambledDiffable exporter first and see if the problem still persists - then you can send me the scrambled version.

**Comment by eleius** [comment]
I've tried again with both OSIS and Zefania sources using the -Dmysword.abbreviation= switch. Now both exported modules work fine, thanks!

As for OSIS, I know its support is only for a "very limited subset", but I wanted to point out that section headings are incorporated into verses. For example:

`<verse osisID="Job.1.1"><head><q>Heading here</q><p eID="1435" /><p sID="1436" /></head>Full verse here.</verse>`

becomes: "Heading here Full verse here."

Thanks again for your work.

**Comment by eleius** [comment]
Maybe `-Dmysword.abbreviation=` could be automatically filled in if `<identifier>` is found in the xml?

I noticed the zefania module has the `<identifier>` tag inside `<information>`, while osis has `<identifier type="OSIS">` it inside `<header>`.

**Comment by schierlm** [comment]
Interestingly, I have not encountered any OSIS modules before that use `head` for section headings - in my experience usually `title` is used. Probably you can "fix" that by search&replace. Or use another tool to convert from OSIS, like [BibleDropBox](http://freely-given.org/Software/BibleDropBox/)

About the automatic passing of various metadata between formats, there is certainly a lot that can be improved there (even so much that you can possibly spend months until metadata is optimal for every format pair). I'm trying to track these in #9 in case anyone with lots of free time wants to tackle this.

For me, it is just not worth the time. The "hard" part is getting all the scripture text converted, and in cases where I care about metadata, I edit them manually.

**Comment by eleius** [comment]
Thanks for suggesting BibleDropBox. I'll try and see if can convert verse headings correctly, else I guess I'll just use a regexp and remove them from the source text.
