### ISSUE TITLE
Not working conversion

### ISSUE THREAD

**Issue by outdever** [schierlm/BibleMultiConverter#57]
java -jar BibleMultiConverter-AllInOneEdition.jar MyBibleZone nrt.SQLite3 ZefaniaXML nrt.xml
....
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/home/radzivon/cc/lib/jaxb-impl-2.2.8-b01.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" javax.xml.bind.MarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-complex-type.2.4.a: Invalid content was found starting with element 'BR'. One of '{STYLE, GRAM, SUP}' is expected.]
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:326)
.... and more
```

**Comment by schierlm** [comment]
Thank you for your bug report.

Can you share the input file (attach it to this issue)?

If not, you can try the following

    java -jar BibleMultiConverter-AllInOneEdition.jar MyBibleZone nrt.SQLite3 ScrambledDiffable nrt.txt

    java -jar BibleMultiConverter-AllInOneEdition.jar Diffable nrt.txt ZefaniaXML nrt.xml

My expectation is that the first one will succeed, yet the second one will fail. nrt.txt is irreversible scrambled (words are replaced by random gibberish), but it also shows the bug, so you should be able to share the file with me.

Or you could run

    java -jar BibleMultiConverter-AllInOneEdition.jar MyBibleZone nrt.SQLite3 Validate

to see if the input file is consistent. some MyBibleZone files are not, unfortunately, which makes them more likely trigger bugs in other formats.

**Comment by outdever** [comment]
Hello.Attached is the archive from which the conversion was carried out.  When checking (with Validate option), it gives the same warnings as when converting, and another program error.  Is it possible to somehow convert with ignoring warnings?Best regards18 янв. 2022 г. 00:32 пользователь Michael Schierl ***@***.***> написал:
Thank you for your bug report.
Can you share the input file (attach it to this issue)?
If not, you can try the following
java -jar BibleMultiConverter-AllInOneEdition.jar MyBibleZone nrt.SQLite3 ScrambledDiffable nrt.txt

java -jar BibleMultiConverter-AllInOneEdition.jar Diffable nrt.txt ZefaniaXML nrt.xml

My expectation is that the first one will succeed, yet the second one will fail. nrt.txt is irreversible scrambled (words are replaced by random gibberish), but it also shows the bug, so you should be able to share the file with me.
Or you could run
java -jar BibleMultiConverter-AllInOneEdition.jar MyBibleZone nrt.SQLite3 Validate

to see if the input file is consistent. some MyBibleZone files are not, unfortunately, which makes them more likely trigger bugs in other formats.

**Comment by schierlm** [comment]
It seems that GitHub ate your attachment for breakfast. Can you try attaching it via the website,  or send directly to `schierlm AT gmx DOT de`?

Warnings are supposed to be ignored, but in this case it seems that the conversion results in some malformed XML tags that cannot be written to the file. The validation error might have given a clue what went wrong.

**Comment by outdever** [comment]
and I was renamed files in archive before conversion
[NRT(1).zip](https://github.com/schierlm/BibleMultiConverter/files/7891541/NRT.1.zip)

**Comment by schierlm** [comment]
Nightly build that contains the fix: https://nightly.link/schierlm/BibleMultiConverter/workflows/main.yaml/master/BibleMultiConverter-AllInOneEdition-Release.zip
