### ISSUE TITLE
Impossible to convert

### ISSUE THREAD

**Issue by LAfricain** [schierlm/BibleMultiConverter#61]
Hi,
I'm very interesting tu use this tool. But I didn't succeed to use it:
First I move in the folder were I can find the BibleMultiConverter.jar script. Then I run it, with one zefaniah file and with one unboundbible file:
```
java -jar BibleMultiConverter.jar UnboundBible spanish_1909.txt OSIS
Exception in thread "main" java.io.IOException: 1	1	1	EN el principio cri� Dios los cielos y la tierra.
	at biblemulticonverter.format.UnboundBible.doImport(UnboundBible.java:162)
	at biblemulticonverter.Main.main(Main.java:66)
```
Zephaniah:
```
java -jar BibleMultiConverter.jar ZefaniaXML SF_2004-11-13_FRE_DEJER_\(LA\ BIBLE\ DE\ JÉRUSALEM\).xml OSIS
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at biblemulticonverter.format.OSIS.doExport(OSIS.java:981)
	at biblemulticonverter.Main.main(Main.java:67)
```
Thank you for your help

**Comment by schierlm** [comment]
Hello,

there are two issues:

First, OSIS format needs export argumenty, you can see them when you run

    java -jar BibleMultiConverter.jar help OSIS

At least a filename is required, and you can also give options to decide which element tags you want milestoned or unmilestoned in case the input texts provides multiple options (e.g. verses across paragraphs or quotations across verses/paragraphs).


Second, your UnboundBible file looks incomplete and has a charset issue. The file should start with a header that looks similar to

    #THE UNBOUND BIBLE (www.unboundbible.org)

Also the charset should be UTF-8. I am surprised that you tried an Unbound Bible input file, considering that the Unbound Bible repository is no longer available online.

**Comment by LAfricain** [comment]
Thank you for the answer. For osis this work well:
`java -jar BibleMultiConverter.jar ZefaniaXML SF_2004-11-13_FRE_DEJER_\(LA\ BIBLE\ DE\ JÉRUSALEM\).xml OSIS BJ.osis.xml`
For unboundbible, I just discovered that their website is now no more available. But your were correct, my file had a missing part. With an other file it's working well:
```
java -jar BibleMultiConverter.jar UnboundBible estonian.txt OSIS Est.osis.xml`

Now I tried with the usfm file, but it won't work:
`java -jar BibleMultiConverter.jar UnboundBible estonian.txt USFM usfm
WARNING: Skipping unsupported book METADATA
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at biblemulticonverter.format.paratext.AbstractParatextFormat.doExportBooks(AbstractParatextFormat.java:432)
	at biblemulticonverter.format.paratext.AbstractParatextFormat.doExport(AbstractParatextFormat.java:360)
	at biblemulticonverter.Main.main(Main.java:67)
```
Your software is amazing, I'm a volunteer of Crosswire, it can help a lot. What bible software do you use?
I have been thinking for a long time that we should get together, and work all together on one software, rather than scattering all these resources in a multitude of biblical software.
For me in opensource software Xiphos and bibletime remain very good software, even if xiphos is getting old because of the lack of developers.

**Comment by schierlm** [comment]
Hello,

I am curious if you read the `help USFM` output? If not, it should explain your problem. If yes, I'm open to suggestions how to make it more clear what you have to give as second export argument.

On my mobile phone i use https://mybible.zone/ (previously I used PalmBible+ on my PDA), and on Desktop for everyday use I still use old (discontinued) MyBible.DE (which uses Zefania XML format). I like the feature set of that software, and the fact it can cope with reordered and split verses well (which is a problem with SWORD formats unless there is an explicit versification format that supports it). On the other hand, all my bibles follow more or less the same versification, so versification format support (which is strong in SWORD) is no need for me.

When looking at commercial software: I also have Logos (the "free as in beer" Core edition with a few commercial resources I got at some promotions/giveaways) installed on my desktop. Its features (especially cross-reference datasets) are really impressive, but you can easily spend lots of money on commercial resources (both Bibles and datasets). Of course it depends on whether you find it faithful to analyze the Bible in such ways (e.g. search verses where Peter talks to Jesus while they are near Jerusalem). They also have licensed most contemporary bible translations used in Europe, so maybe they are the only option to get your favourite bible legally in an offline Bible app.

YouVersion provides free online use of many contemporary bible texts (technically it is not free, as they pay the royalties by donations they receive) but they prohibit download or offline use of their texts.

That being said, SWORD is a great project, if you are fine with old Bible translations and your Bible texts mostly match one of the provided versifications, you get great cross-referencing between different versifications and all of that free (as in speech).

**Comment by schierlm** [comment]
> What other software use Zefania xml format?

Zefania XML is natively used by SongBeamer. Also, in the beginning, some Bible software (like theWord, e-Sword) provided import/convert functionality for Zefania XML files (which disappeared once those programs had a community and many modules in their own native formats). Same applies for most converter programs - Zefania XML as the "smalled common denominator" is usually supported.

I'm closing this issue now. Feel free to reply/reopen in case there are still things open.
