### ISSUE TITLE
Whitespace missing

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#63]
Hi, in converting USFM -> USX3 I've noticed that it results in no whitespace when a verse starts mid-paragraph:

```
\v 4 And this write we vnto you that oure ioye maye be full. 
\v 5 And this is the tydynges which we have hearde of him and declare vnto you that god is lyght and in him is no darknes at all 
```

```
<verse number="4" style="v" sid="1JN 1:4"/>And this write we vnto you that oure ioye maye be full.<verse eid="1JN 1:4"/><verse number="5" style="v" sid="1JN 1:5"/>And this is the tydynges which we have hearde of him and declare vnto you that god is lyght and in him is no darknes at all<verse eid="1JN 1:5"/>
```

[source](https://ebible.org/Scriptures/engtnt_usfm.zip)

I then convert the USX to HTML and it leaves no space between words (in this case `be full.And this`) because there's none in the USX either.

I saw some discussion possibly relating to this in https://github.com/schierlm/BibleMultiConverter/pull/39 but don't know what the conclusion was?

**Comment by schierlm** [comment]
You should be able to get the space back by passing `"-Dbiblemulticonverter.paratext.usx.verseseparatortext= "` as an argument to your Java process (before the `-jar`).

In my opinion, that behaviour should be the default, but you have seen that there has been some discussion about it.

**Comment by shadow-light** [comment]
That worked, thanks!

Yes seems like it should be the default. I wonder whether paratext does it too?
