### ISSUE TITLE
From .chm format to EquipdEPUB format

### ISSUE THREAD

**Issue by erngab** [schierlm/BibleMultiConverter#66]
Hello!
I want to convert one Bible from **.chm** format to EquipdEPUB format. Is there any way I can do this?
Plan for epub formats?
I have the Bible that I want to convert in .chm and .epub formats.

**Comment by schierlm** [comment]
CHM is - like EPUB - just a container for HTML files. You can, for example, extract it with 7-Zip.

But then, from my experience, every EPUB or CHM requires some manual work to identify where which book starts, and to replace the chapter and verse markers. If the remaining text is just plain text, you may succeed by creating a VPL or USFM from it; if there is some more formatting, probably Diffable, Zefania XML or RoundtripHTML may be a start format for converting to your destination format(s).

As you are only interested in Equipd, maybe it could be even simpler to take the HTML, rename the books, replace the tags that Equipd needs to jump to verses, and repackage as an Epub. Having worked with various differently structured EPUB files so far, I don't see any way to automate this in BibleMultiConverter.

Sorry for that.
