### ISSUE TITLE
Is `ide` valid in USX?

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#67]
This is pretty minor but I'm not sure if the `ide` tag is valid in USX. It is [valid in USFM](https://ubsicap.github.io/usfm/identification/index.html#index-3) and is in the docs, but I can't find it in the USX docs. I assume because character encoding declaration is already handled by XML so there's no need for a specific tag for it.

**Comment by schierlm** [comment]
In my opinion the `\ide` tag is only valid in USFM, and not in USX or USFX.

The system should also behave as such:
- When converting from USFM, text is read accordingly
- When converting to USFM, `\ide UTF-8` is written and the file is written as UTF-8
- Neither USFX nor USX formats have any special logic concerning the `\ide` tag.

The only path where I am unsure is when you use `ParatextConverter` to convert USFM to one of the other Paratext formats. In that case, `ide` tag gets stored in the book attributes and *may* (did not verify this though) be written out to other Paratext formats. Pinging @Rolf-Smit as he overhauled the USFX/USX support in commit 891a99692fcdc0ac8cc0b57c60ca07fa53c249e7, which probably introduced this change.

**Comment by shadow-light** [comment]
Yes that was my thinking, but when converting from USFM to USX using ParatextConverter the `ide` is getting written out as a para element:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<usx version="3.0"><book code="1CH" style="id">World English Bible (WEB)</book>
  <para style="ide">UTF-8</para>
  <para style="h">1 Chronicles</para>
  <para style="toc1">The First Book of Chronicles</para>
```

I'm simply ignoring it now when converting to HTML but it might be good to get rid of in case future projects get stuck trying to parse it.

**Comment by schierlm** [comment]
Thank you for confirming my suspicion.

@Rolf-Smit, do you remember why you added the '\ide` tag to the book attributes?

https://github.com/schierlm/BibleMultiConverter/blob/73070c0fd5e0516c4706e4dce570d9132494aa68/biblemulticonverter/src/main/java/biblemulticonverter/format/paratext/USFM.java#L260


If not, I'll remove it (and the check to avoid writing it out for USFM export in https://github.com/schierlm/BibleMultiConverter/blob/73070c0fd5e0516c4706e4dce570d9132494aa68/biblemulticonverter/src/main/java/biblemulticonverter/format/paratext/USFM.java#L294-L296 as well).

**Comment by Rolf-Smit** [comment]
@schierlm I don't remember why it was added. Maybe it was to preserve the original encoding? But that doesn't make sense anyways, since USFM is always written out as UTF-8 and other formats like USX must be written in UTF-8.

I would say, remove it.

**Comment by shadow-light** [comment]
Thanks!

**Comment by shadow-light** [comment]
It turns out apparently it is valid. I discovered that not all elements are documented but can still be found in the schema: https://github.com/ubsicap/usx/blob/master/schema/usx.rng

`ide` is there, but as we discussed it doesn't really have any value as encoding is handled at the XML level, and if you want to convert back to USFM you could potentially choose whatever encoding you liked.

(no action needed, just thought I'd document this for future readers)
