### ISSUE TITLE
Bible name not found

### ISSUE THREAD

**Issue by MichaelJgit** [schierlm/BibleMultiConverter#71]
In attempting to convert an .odt file to .usx, I received the following error: 

>java -jar .\BibleMultiConverter-AllInOneEdition.jar RoundtripODT "C:\temp\Sovereign Creator has Spoken - Pickering 2016.odt" USX c:\temp\output\sov.usx
Exception in thread "main" java.io.IOException: Bible name not found!
        at biblemulticonverter.format.RoundtripODT.fromContentXml(RoundtripODT.java:270)
        at biblemulticonverter.format.RoundtripODT.doImport(RoundtripODT.java:255)
        at biblemulticonverter.Main.main(Main.java:66)

What is it looking for in the input file for _Bible name_?
Thanks,
Mike

**Comment by schierlm** [comment]
Can you tell me where you obtained the ODT file from? The `Roundtrip...` formats are intended that you convert an existing Bible text to that format, then edit it in e.g. LibreOffice, then convert it back or to another format.

RoundtripODT uses style templates to mark bible name, chapter and verse numbers etc. Convert an existing Bible to this format and you will see how it works.

For converting any pre-existing version of Pickering 2016 to USX; I would start with the USFM (or USFX) download available at https://ebible.org/details.php?id=engf35

**Comment by MichaelJgit** [comment]
Hi Michael,

Thank you for the clarification. I received the ODT file from the author of the translation, Dr. Pickering. Looking at the files for the site you referenced, the USFM version is broken up into separate usfm files for each book. The USFX has a series of xml files, with the principal file being the entire NT. Would I provide the zip file as input to BibleMultiConverter, a directory path to the unzipped set of files, or simply the principal xml file?

For instance,
java -jar .\BibleMultiConverter-AllInOneEdition.jar USFX "C:\temp\engf35_usfx.xml" USX c:\temp\output\sov.usx

My goal is to provide a USX file for eSword & YouVersion.

Unfortunately, the eBible.org files are the 2nd edition and Dr. Pickering has published a 3rd edition. I'll have to see if he can provide the USFX files for the 3rd edition as well.

Blessings,
Mike

**Comment by schierlm** [comment]
I would suggest to unzip the USFM version and point BibleMultiConverter to the resulting directory.
Which is also mentioned in `java -jar BibleMultiConverter-AllInOneEdition.jar help USFM`

If the text is indeed newer edition and has been manually edited, expect a lot of manual work. In my experience, Word and ODT versions are the worst (as they tend to include hidden details and subtly different formatting). Any structured format (like US* or Zefania XML or even one verse per line as a text file) tend to be easier to import. And when there are only unstructured formats available, with HTML or EPUB you can at least search and replace tags until you get it to a format that can be converted (Still a lot of manual work).

**Comment by MichaelJgit** [comment]
Thank you!
