### ISSUE TITLE
Issue using "-inline" to convert Bible with more than one verse per line

### ISSUE THREAD

**Issue by amrhone** [schierlm/BibleMultiConverter#72]
I'm having trouble converting a USFM file to Logos.html with more than one verse per line. The command I've been inputting is below:

`java -jar BibleMultiConverter-AllInOneEdition.jar USFM WEB LogosHTML WEB.html Bible -inline`

I'm assuming the issue is with how I've input the command (I'm inexperience in using the command line). Any help with this issue would be appreciated.

**Comment by schierlm** [comment]
The order of arguments is `<outfile> <versemap> <template> <flags>`. You are missing the template, which may be `-`.

`java -jar BibleMultiConverter-AllInOneEdition.jar USFM WEB LogosHTML WEB.html Bible - -inline` should work for you.

**Comment by amrhone** [comment]
That worked. Thank you for your help!
