### ISSUE TITLE
Trouble converting USFM with Strong's numbers to LogosHTML

### ISSUE THREAD

**Issue by amrhone** [schierlm/BibleMultiConverter#73]
I've been able to successfully convert the USFM file to LogosHTML format, however, when it converts the Strong's numbers are still visible and all the words are crossed out. This is also how the Bible appears once it's imported into Logos. Is there a way correct this issue, or will I need a USFM source file without the Strong's numbers?

The command I'm using to complete the conversion is below: 
`java -jar BibleMultiConverter-AllInOneEdition.jar USFM WEB LogosHTML WEB.html Bible - -inline`

I've also noticed that I'm getting a lot of warnings like the ones below during the conversion process:
`WARNING: Skipping unknown tag \q22`
`WARNING: Skipping text outside of verse/headline/prolog
``WARNING: Added whitespace 
[World English Bible_T.docx](https://github.com/schierlm/BibleMultiConverter/files/9689383/World.English.Bible_T.docx)
[World English Bible_T.docx](https://github.com/schierlm/BibleMultiConverter/files/9689385/World.English.Bible_T.docx)
between adjacent grammar tags`

![Screenshot 2022-09-30 215317](https://user-images.githubusercontent.com/19896327/193382393-ec22a5f0-e9d7-4e47-b68e-a9e71761449f.jpg)

**Comment by schierlm** [comment]
As described in [the README](https://github.com/schierlm/BibleMultiConverter#logos-bible-software-export), exporting Strongs and Morphology information to Logos requires an extra step. After converting the HTML file to .docx, run `LogosNestedHyperlinkPostprocessor ` on the resulting .docx file. If the documentation is unclear, I'm open to suggestions how to improve it.

Alternatively, you can first convert to `StrippedDiffable` format which is like Diffable but some information (like Strongs and Morphology) can be stripped. Then convert the resulting file (without Strongs and morphology information) from `Diffable` to `LogosHTML`.

**Comment by amrhone** [comment]
Thank you for your help. I completely overlooked the fact that there was an extra step needed.
