### ISSUE TITLE
Help with command line

### ISSUE THREAD

**Issue by WJSwan1945** [schierlm/BibleMultiConverter#74]
Dear Michael,
I have a USFM formatted Bible which I wish to convert to theWord format. I tried the following command line:
C:\BMC>java -jar BibleMultiConverter-AllInOneEdition.jar USFM t4t.USFM TheWord
I get an error that says t4t.USFM is not a directory.
What am I doing wrong?

My input file's name is t4t.USFM

Kind regards,
Willem

**Comment by schierlm** [comment]
Probably you already solved it yourself, but for others:

USFM expects that you have a directory that contains one file per Bible book.

**Comment by WJSwan1945** [comment]
Thank you, yes I managed to figure it out. Great program, well done!
