### ISSUE TITLE
Markdown output format

### ISSUE THREAD

**Issue by lexiconwriter** [schierlm/BibleMultiConverter#76]
Would be nice to have such a converter to prepare the bible format of https://github.com/kuchejak/obsidian-bible-linker-plugin

**Comment by schierlm** [comment]
Do you have any more information about that format, or sample files?

In particular, Markdown does not have a standard way to express footnotes, so there may be some convention how to handle them.

Hyperlinks to Dictionaries are another point (how to format the destination?)

Are headlines (apart from the headlines that contain the verse numbers) supported? Can there be an introduction text before Verse 1? Can verse numbers have suffixes (e.g. 1a, 1b) and/or can they be reordered?

Also, how to represent Bible features like Strong Numbers or morphology tags? (e.g. Hyperlinks, but which target?)

In the long run, I may eventually find time to install Obsidian and try it myself, but at the moment I cannot give any ETA. Having the details available without having to figure them out myself would help here.

**Comment by lexiconwriter** [comment]
There are two plugins for Obsidian.md: The first one is the above mentioned Bible linker (I use). The author tells us (https://github.com/kuchejak/obsidian-bible-linker-plugin#requirements) he based his project on https://forum.obsidian.md/t/bible-study-in-obsidian-kit-including-the-bible-in-markdown/12503

His own example is extreme simple:

https://github.com/kuchejak/obsidian-bible-linker-plugin#example-file

So it seems he only uses the bible text and no further comments or footnotes today. For me it's a perfect starting point.

**Comment by schierlm** [comment]
I personally like the format used by https://github.com/selfire1/BibleGateway-to-Obsidian (have one page per chapter and use H6 headlines for the verses), so I based my implementation on that one. Verses can still be included with `![[Bk 1#2]]` syntax. But I assume the files will also work as input for the project you use (not tested though).

Note that I do convert headlines, footnotes and simple formatting (bold, italic); and also if you allow inline HTML, I convert Strongs and some more formatting. It looks usable in Obsidian. If you don't like those (or they interfere with your postprocessing), you can always strip them during the conversion process.

**Comment by schierlm** [comment]
Nightly build: https://nightly.link/schierlm/BibleMultiConverter/workflows/main.yaml/master/BibleMultiConverter-AllInOneEdition-Release.zip
