### ISSUE TITLE
Importing interlinear information from MySword bibles

### ISSUE THREAD

**Issue by paul1149** [schierlm/BibleMultiConverter#79]
I downloaded a Bible text from mysword.info. The file name is `OpenGNT.bbl.mybible`. I was surprised to see a MySword file with the .mybible extension. 

I tried to import it into MyBible on Android:

    java -jar BMC.jar MySword OpenGNT.bbl.mybible MyBibleZone OpenGNT.bbl

but I only got a file with verse locations but no verse text.

Clearly I'm doing something wrong!

**Comment by schierlm** [comment]
> I downloaded a Bible text from mysword.info. The file name is OpenGNT.bbl.mybible. I was surprised to see a MySword file with the .mybible extension.

That is normal. MySword Bible files are called .bbl.mybible and MyBible.Zone files are called .sqlite3. (Old Desktop MyBible used .xml).

>but I only got a file with verse locations but no verse text.
>Clearly I'm doing something wrong!

(Un)fortunately not. MySword bible files have two differen options to encode the content. As verse text or as interlinear information. The [bible module you mentioned](https://mysword-bible.info:4443/download/getfile.php?file=OpenGNT.bbl.mybible.zip) contains only interlinear information and (apart from a few line breaks) no verse text.

Importing interlinear information from MySword files is not yet supported, also MyBible.Zone has no direct representation that could represent all the features included in interlinear information. You will also see a warning similar to

    WARNING: Skipping <Q> interlinear information

What is your goal?

When your goal is to just extract one of the text lines along with its Strong / RMAC information, support could be added relatively quickly. When you want to extract all/multiple of the text lines and somehow format them differently in MyBible.Zone, that would be more complicated.

**Comment by paul1149** [comment]
Ok, thanks. I appreciate the detailed explanation. Complicated business, eh?

My goal is still to get a Bible text, I prefer an eclectic one, along the lines of 
`GreekWord ^Strongs+Morphology`
I prefer not to have the English alongside, as I use a parallel window for that.

**Comment by schierlm** [comment]
Try the latest nightly build

https://nightly.link/schierlm/BibleMultiConverter/workflows/main.yaml/master/BibleMultiConverter-AllInOneEdition-Release.zip

and run as

    java -Dmysword.interlinearpattern=@G -jar BMC.jar MySword OpenGNT.bbl.mybible MyBibleZone OpenGNT.bbl

Should give you greek text, strongs and morphology (some morphology tags do not follow RMAC rules and will get stripped, though).

**Comment by paul1149** [comment]
Thanks much! That drew a lot of incorrect formatting errors, but apparently they are insignificant. The end result looks great here. Much appreciated.
