### ISSUE TITLE
CCEL's ThML xml?

### ISSUE THREAD

**Issue by syahzuan** [schierlm/BibleMultiConverter#84]
1. First of all, many thanks for your wonderful work on this repo. What a pleasant surprise to find this amazing project!
2. One question: Does the converter by any chance support ThML-flavoured xml from ccel.org's ?

**Comment by schierlm** [comment]
ThML from ccel.org is not (yet) supported - never heard of that.

Did you want to use it as an export or as an import format?

In case of export format: What programs are there that consume ThML?
In case of import format: Which modules are available in this format? Especially interesting whether there are any modules in ThML that are not available (in comparable quality) in other formats.

**Comment by schierlm** [comment]
Closed due to lack of feedback
