### ISSUE TITLE
Import Beblia xml bibles

### ISSUE THREAD

**Issue by zedimus** [schierlm/BibleMultiConverter#85]
I been trying to import Beblia xml bibles but cant seem to get them to import. Could these be added as an import option ?

https://github.com/Beblia/Holy-Bible-XML-Format

Thanks

**Comment by schierlm** [comment]
Note that I opened  a pull request Beblia/Holy-Bible-XML-Format#2 where I fixed a few XML errors - so in case this is not yet merged, you may want to pull your bibles from that branch.
