### ISSUE TITLE
Support OliveTree csv format

### ISSUE THREAD

**Issue by meichthys** [schierlm/BibleMultiConverter#86]
[OliveTree Bible ](https://www.olivetree.com/) has a csv export option. It would be very nice to be able to convert that export into a sword-compatible (or other Bible software formats).

Here is a short sample of an Olivetree Export
[OliveTreeExportSample.csv](https://github.com/schierlm/BibleMultiConverter/files/14077599/OliveTreeExportSample.csv)

**Comment by schierlm** [comment]
Looking at the sample, it is unclear to me how to convert this into a Bible/Scripture module of any kind. BibleMultiConverter has no support for Commentary or Dictionary modules, and I do not plan to change this.
