### ISSUE TITLE
Using a Property file to override values in the info table?

### ISSUE THREAD

**Issue by paul1149** [schierlm/BibleMultiConverter#88]
I convert theWord Bible modules to MyBibleZone format, and it's been going great. After I do so I use a DB editor to change a few Info values, but I see in my notes that this can be done automatically via a Properties File. But I don't see any note of it here. Could someone point me to where this is explained? Thanks much!

**Comment by paul1149** [comment]
Or as an alternative, does anyone know how to include values such as `Description` in the original theWord module, so they get carried over to the sqlite3 file? Thanks.

**Comment by schierlm** [comment]
The explanation is indeed only a oneliner in `help MyBibleZone` output.

The property file follows Java's [Properties format](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-) (the plaintext one).

The property names are the same as the entries in Info table, and the values can use `${name}` to refer to the Bible name, or same syntax `${foo}` with different names to refer to any metadata attributes of the bible.

However, TheWord importe does not set any metadata attributes yet (see also #9 ), so currently the only way is to hardcode it like in the following example:

```
description=The description of the module.
detailed_info=Some more details
````

**Comment by paul1149** [comment]
Ok, thanks. theWord has limited support for attributes, and even the ones that do translate to the MyBibleZone format are not being picked up. So I guess this will remain a manual task.
