### ISSUE TITLE
Problem when converting TheWord bible to MyBibleZone

### ISSUE THREAD

**Issue by 1p1v4** [schierlm/BibleMultiConverter#95]
```
% java -jar BibleMultiConverter-AllInOneEdition.jar TheWord ../ChinLZZt.ont MyBibleZone
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at biblemulticonverter.sqlite.format.MyBibleZone.doExport(MyBibleZone.java:603)
	at biblemulticonverter.Main.main(Main.java:67)
```

I got problem when reading TheWord module.

**Comment by schierlm** [comment]
In fact, loading the TheWord module likely worked fine, your error messages is caused by the missing output filename at the end of the command line. See `help MyBibleZone` for more details.

**Comment by 1p1v4** [comment]
Oh! Sorry, my bad.  Thanks for pointing out my silly fault.
