### ISSUE TITLE
USFM: Could not insert verse end

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#98]
Another occurrence of the issue noted in #96 

Your fix worked for a number of translations, but here's one more that still threw the error. Perhaps because it has trailing whitespace for the empty verse?

[luk.usfm.txt](https://github.com/user-attachments/files/18251208/luk.usfm.txt)

`Could not insert verse end of 36 [LUK 17:36], because no suitable location could be found.`

**Comment by schierlm** [comment]
In fact, the whitespace has already been stripped. The problem here is an empty paragraph, a paragraph marker, and the next paragraph also being empty. Will push a fix for this.

**Comment by schierlm** [comment]
Thanks for reporting. Indeed, it is the same issue (verse start just before chapter end (or file end). Will push a fix.

And thanks for converting all eBible files. I've done the same a few years ago and fixed many USFM issues, but there get new ones introduced as well as changes happen to the bibles as well..
