### ISSUE TITLE
USX: Support "usfm" para style

### ISSUE THREAD

**Issue by shadow-light** [schierlm/BibleMultiConverter#99]
Apparently `<para style="usfm">3.0</para>` is valid in the header section of USX, before the first chapter begins. BMC currently throws an error when encountering it `NullPointerException: Cannot invoke "biblemulticonverter.format.paratext.ParatextBook$ParagraphKind.getVersion()" because "kind" is null`

[See USX schema](https://github.com/ubsicap/usx/blob/73e909038b46bfc8bfae017d5c1e747d85a690fa/schema/usx.rnc#L274)

When converting back to USFM, I guess this element is just ignored?

**Comment by schierlm** [comment]
Yes, it should be ignored/skipped when importing USX3, since USFM will synthesize the `\usfm 3.0` tag automatically if any features not supported by USFM 2 are present. Will push a fix.

**Comment by schierlm** [comment]
Fixed in 6e053b4f1bf8f422e667138e0a869215a0d476ab, and nightly version has been rebuilt.
